@WebApiDowntime_HostAddress = http://localhost:5048

GET {{WebApiDowntime_HostAddress}}/api/DownTime/downtime?2024-11-13T00:00:00
Accept: application/json

###

GET {{WebApiDowntime_HostAddress}}/api/DownTime/ComparisonResults
Accept: application/json

###

Put {{WebApiDowntime_HostAddress}}/api/DownTime/SetComparisonResults
