@WebApiDowntime_HostAddress = https://192.168.100.100:5048

GET {{WebApiDowntime_HostAddress}}/api/DownTime/downtime?date=2024-10-05T00:00:00
Accept: application/json

###

GET {{WebApiDowntime_HostAddress}}/api/DownTime/downtime?date=2024-10-05T08:05:00
Accept: application/json

###

GET {{WebApiDowntime_HostAddress}}/api/DownTime/downtime?date=2024-10-05T20:05:00
Accept: application/json

###

GET {{WebApiDowntime_HostAddress}}/api/DownTime/ComparisonResults
Accept: application/json

###

Put {{WebApiDowntime_HostAddress}}/api/DownTime/SetComparisonResults

###
GET {{WebApiDowntime_HostAddress}}/api/Macaddressregistry/CheckIp
Accept: application/json

###
GET {{WebApiDowntime_HostAddress}}/api/Macaddresstables/GetIpAsync?serverName=server
Accept: application/json